import { TANOD_SCHEMA_VERSION } from './compat.js';
import { resolveCapacity } from './capacity.js';
import { normalizeRouteName, policyFingerprint, validatePolicy } from './policy.js';
import { Lines, inlineList, quote } from './yaml.js';

/**
 * Turn a Next dynamic route into a Tanod path glob.
 *
 *   /products/[slug]      -> /products/*
 *   /blog/[...slug]       -> /blog/**            (not /blog itself, as in Next)
 *   /shop/[[...slug]]     -> {/shop,/shop/**}    (Next matches /shop too)
 *
 * Tanod compiles globs without `literal_separator`, so `*` crosses `/`:
 * `/products/*` also matches `/products/a/b`. That is measured, not assumed,
 * and it is why generated dynamic routes default to a private class — an
 * over-matching pattern with a private policy costs a little reuse, while an
 * over-matching pattern with a public one is a correctness problem.
 */
export function toGlob(page) {
  const optional = page.match(/^(.*)\/\[\[\.\.\.[^\]]+\]\]$/);
  if (optional) {
    const parent = optional[1] || '';
    return `{${parent || '/'},${parent}/**}`;
  }
  return page.replace(/\/\[\.\.\.[^\]]+\]/g, '/**').replace(/\[[^\]]+\]/g, '*');
}

/** A stable, readable, unique route id derived from a page path. */
export function routeId(page, taken) {
  const base =
    page
      .replace(/\[\[?\.{0,3}([^\]]*?)\]?\]/g, '$1')
      .replace(/[^a-zA-Z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .toLowerCase() || 'root';
  let id = base;
  let n = 2;
  while (taken.has(id)) id = `${base}-${n++}`;
  taken.add(id);
  return id;
}

/** Is this app-router route a Route Handler rather than a page? */
function isRouteHandler(appPaths, page) {
  return Object.entries(appPaths).some(([file, route]) => route === page && file.endsWith('/route'));
}

/**
 * Generate a Tanod configuration from a Next build.
 *
 * The governing rule is that **anything the build does not prove is shareable
 * is private**. A prerendered route is proof: Next generated one response for
 * everybody, so it can be shared with everybody. A dynamically rendered route
 * is not proof of anything — it may read cookies, headers or a session — so it
 * is generated as `private_dynamic` with a comment saying how to opt in.
 *
 * That direction is deliberate. A generator that guessed `public_ssr` would be
 * one bad guess away from serving one user's page to another, and it would do
 * it silently, in a file nobody reads closely because a tool wrote it.
 */
export function generateConfig(build, options = {}) {
  const {
    includeDeployment = true,
    staleIfError = '1m',
    upstreams = [],
    lowPriorityPercent = 30,
    policy: policyInput = null,
    rollout = 'cache',
  } = options;
  if (!['observe', 'protect', 'coalesce', 'cache'].includes(rollout)) {
    throw new TypeError(`rollout must be observe, protect, coalesce, or cache; got ${rollout}`);
  }
  const capacity = resolveCapacity(options);
  const concurrency = capacity.concurrency;
  const policy = policyInput ? validatePolicy(policyInput, build) : { version: 1, routes: {} };
  const imageUsesPriority = upstreams.length === 0 || concurrency > 1;
  const imageWeight = upstreams.length > 0
    ? Math.min(4, Math.max(1, concurrency - 1))
    : 4;
  const effectiveLowPriorityPercent = upstreams.length > 0 && imageUsesPriority
    ? Math.max(lowPriorityPercent, Math.ceil((imageWeight * 100) / concurrency))
    : lowPriorityPercent;
  const base = build.basePath || '';
  const p = (suffix) => `${base}${suffix}`;
  const taken = new Set();
  const out = new Lines();

  out.comment(
    'Generated by @tanod/next from a Next.js build. Do not edit by hand:\n' +
      'regenerate after each build so `deployment.id` and the route list stay in\n' +
      'step with what is actually deployed.\n' +
      '\n' +
      `Next build id:      ${build.buildId}\n` +
      `Deployment identity: ${build.identity ?? build.buildId}\n` +
      `Build fingerprint:  ${build.fingerprint ?? 'unavailable'}\n` +
      `Policy fingerprint: ${policyFingerprint(policyInput)}\n` +
      `routes-manifest:    v${build.manifestVersions.routes}\n` +
      `prerender-manifest: ${build.manifestVersions.prerender === null ? 'absent' : 'v' + build.manifestVersions.prerender}\n` +
      '\n' +
      'Every route the build does not PROVE is shareable is generated as\n' +
      '`private_dynamic`. Prerendered routes are proof — Next produced one\n' +
      'response for everybody. Dynamically rendered routes are not, because they\n' +
      'may read cookies or headers. Public dynamic routes require an explicit\n' +
      'operator assertion in `tanod.next.yaml`.',
  );
  out.raw(`version: ${TANOD_SCHEMA_VERSION}`);
  out.raw(`mode: ${rollout === 'observe' ? 'observe' : 'protect'}`);

  if (rollout === 'protect' || rollout === 'coalesce') {
    out.raw();
    out.comment(`Rollout stage: ${rollout}. Response caching remains globally disabled.`);
    out.raw('cache:');
    out.raw('  enabled: false');
    out.raw('coalesce:');
    out.raw(`  enabled: ${rollout === 'coalesce'}`);
  }

  if (includeDeployment) {
    out.raw();
    out.comment(
      'The build id. It is part of every cache key, so a new build is never\n' +
        "served the previous build's entries — and a SIGHUP that changes it\n" +
        'purges them.',
    );
    out.raw('deployment:');
    out.raw(`  id: ${quote(build.identity ?? build.buildId)}`);
  }

  if (upstreams.length > 0) {
    out.raw();
    out.comment(
      'Where the Next.js servers are. `concurrency.max` is the one number here\n' +
        'that has to come from your own measurement: it is the ceiling on how\n' +
        'much work the origin is asked to do at once, and the right value is a\n' +
        'property of your renders and your hardware, not of your framework.\n' +
        '\n' +
        '`priorities.low` reserves the rest of that ceiling for page renders, so\n' +
        'a burst of image transforms cannot starve them.',
    );
    out.raw('origin:');
    out.raw(`  upstreams: ${inlineList(upstreams)}`);
    out.raw('  concurrency:');
    out.raw(`    max: ${concurrency}`);
    if (imageUsesPriority) {
      out.raw('  priorities:');
      out.raw(`    low: ${effectiveLowPriorityPercent}`);
    }
  }

  if (capacity.group) {
    out.raw();
    out.comment(
      'Static replica partition. Each Tanod process enforces the local\n' +
        'origin ceiling above; their declared sum cannot exceed this group\n' +
        'budget. Keep the orchestrator at or below `replicas`.',
    );
    out.raw('capacity:');
    out.raw(`  global_max: ${capacity.group.globalMax}`);
    out.raw(`  replicas: ${capacity.group.replicas}`);
  }

  out.raw();
  out.raw('routes:');

  out.raw();
  out.comment('Fingerprinted build output. Immutable, and serving it is not rendering.', 2);
  out.raw(`  - id: ${quote(routeId('next-static', taken))}`);
  out.raw(`    match: ${quote(p('/_next/static/**'))}`);
  out.raw('    class: static');

  out.raw();
  out.comment(
    'The image optimiser. `vary: [Accept]` is load-bearing: Next negotiates the\n' +
      'output format on Accept and answers `Vary: Accept`, so without it in the\n' +
      'key Tanod refuses to store anything and this route gets a 0% hit rate.\n' +
      '`priority: low` and `weight` keep image transforms — several hundred\n' +
      'milliseconds of origin CPU each — from starving page renders.',
    2,
  );
  out.raw(`  - id: ${quote(routeId('next-image', taken))}`);
  out.raw(`    match: ${quote(p('/_next/image'))}`);
  out.raw('    class: public_dynamic');
  if (imageUsesPriority) out.raw('    priority: low');
  out.raw(`    weight: ${imageWeight}`);
  out.raw('    cache:');
  out.raw('      ttl:');
  out.raw('        max: 1h');
  out.raw('      query:');
  out.raw('        mode: include');
  out.raw(`        keys: ${inlineList(['url', 'w', 'q'])}`);
  out.raw('      vary:');
  out.raw(`        headers: ${inlineList(['Accept'])}`);

  if ((build.pagePaths ?? []).length > 0) {
    out.raw();
    out.comment(
      'Pages Router data payloads. They use a different URL from the document\n' +
        'and inherit the document route\'s explicit privacy decision.',
      2,
    );
    for (const page of [...build.pagePaths].sort(compareRouteSpecificity)) {
      const assertion = policy.routes[normalizeRouteName(page)];
      const dataPath = p(`/_next/data/${build.buildId}${toGlob(page === '/' ? '/index' : page)}.json`);
      out.raw(`  - id: ${quote(routeId(`data${page}`, taken))}`);
      emitMatch(out, dataPath, assertion?.methods);
      emitAssertion(out, assertion, rollout);
    }
  }

  const prerendered = Object.entries(build.prerendered)
    .filter(([route]) => !route.startsWith('/_'))
    .sort(([a], [b]) => a.localeCompare(b));
  if (prerendered.length > 0) {
    out.raw();
    out.comment(
      'Prerendered routes. Next generated one response for everybody, which is\n' +
        'what makes `override_origin` correct here rather than a guess: the build\n' +
        'is the evidence.',
      2,
    );
    for (const [route, entry] of prerendered) {
      const revalidate = entry.initialRevalidateSeconds;
      const ttl = typeof revalidate === 'number' && revalidate > 0 ? `${revalidate}s` : '1h';
      out.raw(`  - id: ${quote(routeId(`page${route}`, taken))}`);
      out.raw(`    match: ${quote(p(route))}`);
      out.raw('    class: public_ssr');
      out.raw('    cache:');
      out.raw('      override_origin: true');
      out.raw('      ttl:');
      out.raw(`        max: ${ttl}`);
      out.raw(`      stale_if_error: ${staleIfError}`);
      out.raw('    coalesce:');
      out.raw(`      enabled: ${rollout === 'coalesce' || rollout === 'cache'}`);
    }
  }

  const handlers = [...new Set(Object.values(build.appPaths))]
    .filter((route) => isRouteHandler(build.appPaths, route))
    .sort(compareRouteSpecificity);
  if (handlers.length > 0) {
    out.raw();
    out.comment(
      'App Router route handlers. Generated private: a handler is code, and\n' +
        'nothing in the build says what it reads.',
      2,
    );
    for (const route of handlers) {
      const assertion = policy.routes[normalizeRouteName(route)];
      out.raw(`  - id: ${quote(routeId(`api${route}`, taken))}`);
      emitMatch(out, p(toGlob(route)), assertion?.methods);
      if (assertion?.weight !== undefined) out.raw(`    weight: ${assertion.weight}`);
      if (assertion?.priority !== undefined) out.raw(`    priority: ${assertion.priority}`);
      out.raw('    class: private_dynamic');
      out.raw('    cache:');
      out.raw('      enabled: false');
    }
  }

  const prerenderedSet = new Set(prerendered.map(([route]) => route));
  const handlerSet = new Set(handlers);
  const pages = [...new Set([
    ...[...build.staticRoutes, ...build.dynamicRoutes].map((r) => r.page),
    ...(build.pagePaths ?? []),
  ])]
    .filter(
      (page) => page && !page.startsWith('/_') && !prerenderedSet.has(page) && !handlerSet.has(page),
    )
    .sort(compareRouteSpecificity);
  if (pages.length > 0) {
    out.raw();
    out.comment(
      'Dynamically rendered pages. Private by default — the build does not say\n' +
        'whether these read cookies or headers. Approve public routes by their\n' +
        'Next.js names in a checked-in `tanod.next.yaml`, then regenerate:\n' +
        '\n' +
        '    routes:\n' +
        '      /products/[slug]:\n' +
        '        privacy: public\n' +
        '        cache:\n' +
        '          ttl: 2s\n' +
        '\n' +
        'A dynamically rendered Next route answers `no-store`, so the override is\n' +
        'required or nothing here is ever cached or collapsed. Do not edit this\n' +
        'generated file directly.',
      2,
    );
    for (const page of pages) {
      const assertion = policy.routes[normalizeRouteName(page)];
      out.raw(`  - id: ${quote(routeId(`page${page}`, taken))}`);
      emitMatch(out, p(toGlob(page)), assertion?.methods);
      emitAssertion(out, assertion, rollout);
    }
  }

  out.raw();
  out.comment(
    'Anything not named above. Private, so a route added to the app after this\n' +
      'file was generated is safe rather than shared.',
    2,
  );
  out.raw(`  - id: ${quote(routeId('default', taken))}`);
  out.raw(`    match: ${quote(p('/**'))}`);
  out.raw('    class: private_dynamic');
  out.raw('    cache:');
  out.raw('      enabled: false');

  return out.toString();
}

function emitMatch(out, path, methods) {
  if (!methods) {
    out.raw(`    match: ${quote(path)}`);
    return;
  }
  out.raw('    match:');
  out.raw(`      path: ${quote(path)}`);
  out.raw(`      methods: ${inlineList(methods)}`);
}

function emitAssertion(out, assertion, rollout) {
  if (assertion?.weight !== undefined) out.raw(`    weight: ${assertion.weight}`);
  if (assertion?.priority !== undefined) out.raw(`    priority: ${assertion.priority}`);
  if (assertion?.privacy === 'public') {
    out.raw('    class: public_ssr');
    out.raw('    cache:');
    out.raw('      override_origin: true');
    out.raw('      ttl:');
    out.raw(`        max: ${assertion.cache.ttl}`);
    if (assertion.cache.stale_if_error) out.raw(`      stale_if_error: ${assertion.cache.stale_if_error}`);
    if (assertion.cache.query) {
      out.raw('      query:');
      out.raw('        mode: include');
      out.raw(`        keys: ${inlineList(assertion.cache.query)}`);
    }
    if (assertion.cache.vary) {
      out.raw('      vary:');
      out.raw(`        headers: ${inlineList(assertion.cache.vary)}`);
    }
    out.raw('    coalesce:');
    const coalesceEnabled = rollout === 'protect' ? false : assertion.coalesce ?? true;
    out.raw(`      enabled: ${coalesceEnabled}`);
    if (rollout === 'coalesce' && coalesceEnabled) out.raw('      override_origin: true');
  } else {
    out.raw('    class: private_dynamic');
    out.raw('    cache:');
    out.raw('      enabled: false');
  }
}

function compareRouteSpecificity(left, right) {
  const dynamic = (value) => (value.match(/\[/g) ?? []).length;
  return dynamic(left) - dynamic(right) || right.length - left.length || left.localeCompare(right);
}

/** Describe the decisions used by generate without emitting YAML. */
export function inspectRoutes(build, policyInput = null) {
  const policy = policyInput ? validatePolicy(policyInput, build) : { version: 1, routes: {} };
  const handlers = new Set(
    Object.entries(build.appPaths)
      .filter(([file]) => file.endsWith('/route'))
      .map(([, route]) => route),
  );
  const prerendered = new Set(Object.keys(build.prerendered).filter((route) => !route.startsWith('/_')));
  const pages = new Set(
    [...build.staticRoutes, ...build.dynamicRoutes, ...(build.pagePaths ?? []).map((page) => ({ page }))]
      .map((route) => route.page)
      .filter((route) => route && !route.startsWith('/_')),
  );
  const rows = [];
  for (const route of [...new Set([...pages, ...handlers, ...prerendered])].sort()) {
    const assertion = policy.routes[normalizeRouteName(route)];
    const handler = handlers.has(route);
    const staticPage = prerendered.has(route);
    const isPublic = staticPage || assertion?.privacy === 'public';
    rows.push({
      route,
      match: toGlob(route),
      render: handler ? 'handler' : staticPage ? 'prerendered' : 'dynamic',
      privacy: isPublic ? 'public' : 'private',
      reuse: staticPage
        ? `cache ${typeof build.prerendered[route]?.initialRevalidateSeconds === 'number' ? `${build.prerendered[route].initialRevalidateSeconds}s` : '1h'}`
        : assertion?.privacy === 'public'
          ? `cache ${assertion.cache.ttl}`
          : 'bypass',
      weight: assertion?.weight ?? 1,
      priority: assertion?.priority ?? 'normal',
      evidence: staticPage ? 'Next prerender manifest' : assertion ? 'operator assertion' : 'conservative default',
      publicOverride: !staticPage && assertion?.privacy === 'public',
      assertion: assertion ?? null,
    });
  }
  return rows;
}
